### ISSUE TITLE
Invalid characters in uid cleaned up incorrectly

### ISSUE THREAD

**Issue by levitation** [acsresearch/interlab#64]
Currently the last line in file ```interlab\utils\text.py``` and function
```def generate_uid(name: str) -> str:```
is
```return uid.replace(":/\\", "-")```

This does not work as intended. String replace matches only occurrences of entire search string. 

Intended behaviour can be achieved with this line:
```return re.sub(r"[:/\\]", "-", uid)```

**Comment by spirali** [comment]
Thank you! It is now fixed in the main branch.
